// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGDEF.AccesoDatos;

#nullable disable

namespace SIGDEF.AccesoDatos.Migrations
{
    [DbContext(typeof(SIGDeFContext))]
    [Migration("20251212232511_Inicialv2SolucionEventos-Club")]
    partial class Inicialv2SolucionEventosClub
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGDEF.Entidades.Atleta", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<bool>("BecadoEnard")
                        .HasColumnType("boolean");

                    b.Property<bool>("BecadoSdn")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAptoMedico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoBeca")
                        .HasColumnType("numeric");

                    b.Property<bool>("PerteneceSeleccion")
                        .HasColumnType("boolean");

                    b.Property<bool>("PresentoAptoMedico")
                        .HasColumnType("boolean");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdClub");

                    b.ToTable("Atleta", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.AtletaTutor", b =>
                {
                    b.Property<int>("IdAtleta")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("IdTutor")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAtleta", "IdTutor");

                    b.HasIndex("IdTutor");

                    b.ToTable("AtletaTutor", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Club", b =>
                {
                    b.Property<int>("IdClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClub"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdClub");

                    b.ToTable("Club", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.DelegadoClub", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<int>("ClubIdClub")
                        .HasColumnType("integer");

                    b.Property<int>("IdFederacion")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdPersona");

                    b.HasIndex("ClubIdClub");

                    b.HasIndex("IdFederacion");

                    b.HasIndex("IdRol");

                    b.ToTable("DelegadoClub", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.DocumentacionPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("DocumentacionPersonas");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Entrenador", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<bool>("BecadoEnard")
                        .HasColumnType("boolean");

                    b.Property<bool>("BecadoSdn")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaSeleccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MontoBeca")
                        .HasColumnType("numeric");

                    b.Property<bool>("PerteneceSeleccion")
                        .HasColumnType("boolean");

                    b.Property<bool>("PresentoAptoMedico")
                        .HasColumnType("boolean");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdClub");

                    b.ToTable("Entrenador", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinInscripciones")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioInscripciones")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereCertificadoMedico")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneCronometraje")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdEvento");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.EventoPrueba", b =>
                {
                    b.Property<int>("IdEventoPrueba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEventoPrueba"));

                    b.Property<int>("CategoriaEdad")
                        .HasColumnType("integer");

                    b.Property<int>("Distancia")
                        .HasColumnType("integer");

                    b.Property<int>("IdEvento")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecioCategoria")
                        .HasColumnType("numeric");

                    b.Property<int>("SexoCompetencia")
                        .HasColumnType("integer");

                    b.Property<int>("TipoBote")
                        .HasColumnType("integer");

                    b.HasKey("IdEventoPrueba");

                    b.HasIndex("IdEvento");

                    b.ToTable("EventoPrueba", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Federacion", b =>
                {
                    b.Property<int>("IdFederacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFederacion"));

                    b.Property<string>("BancoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailCobro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TitularCuenta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdFederacion");

                    b.ToTable("Federacion", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int?>("EventoIdEvento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("integer");

                    b.Property<int>("IdEventoPrueba")
                        .HasColumnType("integer");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("EventoIdEvento");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdEventoPrueba");

                    b.ToTable("Inscripcion", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.PagoTransaccion", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer");

                    b.Property<string>("IdMercadoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.HasKey("IdPago");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdPersona");

                    b.ToTable("PagoTransaccion", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdPersona");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Tipo = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Tipo = "PresidenteFederacion"
                        },
                        new
                        {
                            IdRol = 3,
                            Tipo = "DelegadoClub"
                        },
                        new
                        {
                            IdRol = 4,
                            Tipo = "Entrenador"
                        },
                        new
                        {
                            IdRol = 5,
                            Tipo = "EntrenadorSeleccion"
                        },
                        new
                        {
                            IdRol = 6,
                            Tipo = "Atleta"
                        },
                        new
                        {
                            IdRol = 7,
                            Tipo = "Secretario"
                        });
                });

            modelBuilder.Entity("SIGDEF.Entidades.Tutor", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTutor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdPersona");

                    b.ToTable("Tutor", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SIGDEF.Entidades.Atleta", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Club", "Club")
                        .WithMany("Atletas")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.Persona", "Persona")
                        .WithOne("Atleta")
                        .HasForeignKey("SIGDEF.Entidades.Atleta", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIGDEF.Entidades.AtletaTutor", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Atleta", "Atleta")
                        .WithMany("Tutores")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.Tutor", "Tutor")
                        .WithMany("AtletasTutores")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SIGDEF.Entidades.DelegadoClub", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Club", "Club")
                        .WithMany("Representantes")
                        .HasForeignKey("ClubIdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.Federacion", "Federacion")
                        .WithMany("DelegadosClub")
                        .HasForeignKey("IdFederacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.Persona", "Persona")
                        .WithOne("DelegadoClub")
                        .HasForeignKey("SIGDEF.Entidades.DelegadoClub", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.Rol", "Rol")
                        .WithMany("DelegadosClub")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Federacion");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SIGDEF.Entidades.DocumentacionPersona", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Persona", "Persona")
                        .WithMany("Documentacion")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Entrenador", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Club", "Club")
                        .WithMany("Entrenadores")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.Persona", "Persona")
                        .WithOne("Entrenador")
                        .HasForeignKey("SIGDEF.Entidades.Entrenador", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIGDEF.Entidades.EventoPrueba", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Evento", "Evento")
                        .WithMany("Pruebas")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Inscripcion", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Evento", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoIdEvento");

                    b.HasOne("SIGDEF.Entidades.Atleta", "Atleta")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.EventoPrueba", "EventoPrueba")
                        .WithMany()
                        .HasForeignKey("IdEventoPrueba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("EventoPrueba");
                });

            modelBuilder.Entity("SIGDEF.Entidades.PagoTransaccion", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Club", "Club")
                        .WithMany("Pagos")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGDEF.Entidades.Persona", "Persona")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Tutor", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Persona", "Persona")
                        .WithOne("Tutor")
                        .HasForeignKey("SIGDEF.Entidades.Tutor", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Usuario", b =>
                {
                    b.HasOne("SIGDEF.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("IdClub");

                    b.HasOne("SIGDEF.Entidades.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("SIGDEF.Entidades.Usuario", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Club");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Atleta", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Club", b =>
                {
                    b.Navigation("Atletas");

                    b.Navigation("Entrenadores");

                    b.Navigation("Pagos");

                    b.Navigation("Representantes");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Evento", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Federacion", b =>
                {
                    b.Navigation("DelegadosClub");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Persona", b =>
                {
                    b.Navigation("Atleta");

                    b.Navigation("DelegadoClub");

                    b.Navigation("Documentacion");

                    b.Navigation("Entrenador");

                    b.Navigation("Pagos");

                    b.Navigation("Tutor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Rol", b =>
                {
                    b.Navigation("DelegadosClub");
                });

            modelBuilder.Entity("SIGDEF.Entidades.Tutor", b =>
                {
                    b.Navigation("AtletasTutores");
                });
#pragma warning restore 612, 618
        }
    }
}
